[package]
name = "aktor"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3"
async-trait = "0.1"
parking_lot = "0.12.1"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
